inputs:
  path:
    default: .

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
    - shell: bash
      run: bun "$GITHUB_ACTION_PATH/main.ts"
      env:
        INPUT_PATH: ${{ inputs.path }}
