name: Configure Bun action
description: "🧅 Write your GitHub Actions in Bun!"
branding:
  icon: settings
  color: yellow
inputs:
  token:
    default: ${{ github.token }}
  path:
    default: .
runs:
  using: node20
  main: _main.mjs
