name: Configure Bun action
description: 🧅 Write your GitHub Actions using Bun!

branding:
  icon: settings
  color: yellow

inputs:
  token:
    default: ${{ github.token }}
  path:
    default: .

# TODO: Dog-food own action once hits v1 stable
runs:
  using: node20
  main: out/main.js
