name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  bun0:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: jcbhmr/configure-bun-action@v0.10.0
      - id: main
        uses: ./
        with:
          path: test/bun0
      - shell: jq -C . {0}
        run: ${{ toJSON(steps.main.outputs) }}
      - uses: ./test/bun0
  bun1:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: jcbhmr/configure-bun-action@v0.10.0
      - id: main
        uses: ./
        with:
          path: test/bun1
      - shell: jq -C . {0}
        run: ${{ toJSON(steps.main.outputs) }}
      - uses: ./test/bun1
