name: Test action
on:
  push:
    branches: "main"
  pull_request:
jobs:
  test-action:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - id: main
        uses: ./
        with:
          path: test
      - shell: jq -C . {0}
        run: ${{ toJSON(steps.main.outputs) }}
      - run: tree -a test
      - run: cat test/action.yml
      - run: cat test/_main.mjs
      - run: cat test/_pre.mjs
      - run: cat test/_post.mjs
