name: Test action
on:
  push:
    branches: "main"
  pull_request:
jobs:
  bun0:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - id: main
        uses: ./
        with:
          path: test/bun0
      - shell: jq -C . {0}
        run: ${{ toJSON(steps.main.outputs) }}
      - run: ls test/bun1
      - run: ls test/bun1/.bun
      - run: cat test/bun0/action.yml
      - run: cat test/bun0/_main.mjs
      - run: cat test/bun0/_pre.mjs
      - run: cat test/bun0/_post.mjs
  bun1:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - id: main
        uses: ./
        with:
          path: test/bun1
      - shell: jq -C . {0}
        run: ${{ toJSON(steps.main.outputs) }}
      - run: ls test/bun1
      - run: ls test/bun1/.bun
      - run: cat test/bun1/action.yml
      - run: cat test/bun1/_main.mjs
      - run: cat test/bun1/_pre.mjs
      - run: cat test/bun1/_post.mjs
