name: Test action
on:
  push:
    branches: "main"
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/test-action.yml"
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/test-action.yml"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  bun0:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: |
          bun build --target=bun --splitting --outdir=out --sourcemap=inline \
            src/main.ts
      - uses: jcbhmr/configure-bun-action@v0.1.0
      - id: main
        uses: ./
        with:
          path: test/bun0
      - shell: jq -C . {0}
        run: ${{ toJSON(steps.main.outputs) }}
      - run: ls -A test/bun0
      - run: ls -A test/bun0/.bun
      - run: cat test/bun0/action.yml
      - run: cat test/bun0/.bun/main.mjs
      - run: cat test/bun0/.bun/pre.mjs
      - run: cat test/bun0/.bun/post.mjs
      - uses: ./test/bun0
        env:
          BUN_DEBUG: true
  bun1:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: |
          bun build --target=bun --splitting --outdir=out --sourcemap=inline \
            src/main.ts
      - uses: jcbhmr/configure-bun-action@v0.1.0
      - id: main
        uses: ./
        with:
          path: test/bun1
      - shell: jq -C . {0}
        run: ${{ toJSON(steps.main.outputs) }}
      - run: ls -A test/bun1
      - run: ls -A test/bun1/.bun
      - run: cat test/bun1/action.yml
      - run: cat test/bun1/.bun/main.mjs
      - run: cat test/bun1/.bun/pre.mjs
      - run: cat test/bun1/.bun/post.mjs
      - uses: ./test/bun1
        env:
          BUN_DEBUG: true
