name: Update versions.json
on:
  push:
    branches: "main"
    paths: .github/workflows/update-versions.yml
  schedule:
    - cron: "17 */6 * * *"
  workflow_dispatch:
jobs:
  update-versions:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v6
        with:
          script: |
            const { writeFile } = require("node:fs/promises");
            const releases = await github.paginate(github.rest.repos.listReleases, {
              owner: "oven-sh",
              repo: "bun",
            });
            const json = {
              bun: releases.flatMap(x => x.tag_name.match(/bun-v\d+\.\d+\.\d+/)?.[0] ?? []),
            };
            await writeFile("versions.json", JSON.stringify(json, null, 2));
      - uses: stefanzweifel/git-auto-commit-action@v5
